### ISSUE TITLE
Default selectbox

### ISSUE THREAD

**Issue by Lengo-UA** [OntimeLengo/ontime-components#3]
1. When choosing the item
then  the choosing item  is displayed on  the input field, button-arrow is 'Up' but **the border is still blue**

2. Unpossible to delete the chose item. 
For example, when User has chosen the item, but he is wrong and wants then this selectbox is still empty

**Comment by OntimeLengo** [comment]
> When choosing the item
then the choosing item is displayed on the input field, button-arrow is 'Up' but the border is still blue

It is a normal behavior because the field changes his border color when it lost focus. But when you select some item the field still has a focus.

> Unpossible to delete the chose item.
For example, when User has chosen the item, but he is wrong and wants then this selectbox is still empty

Please see "Select/Multiselect, clearable, disabled" section in the storybook. Some examples have the Clear button. You have to use "clearable" attribute for this behavior.
